Component Governance re org.apache.logging.log4j vulnerability (#3627)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Fix Django Component Governance security warning

* Fix Django 2.2 before 2.2.10 has a security vulnerability.

* Update log4j-api and log4j-core to 2.15.0

* Update dependency to log4j-to-slf4j:jar:2.15.0

* Delete temp work files

* Update bot SDK references in pom files to 4.14.1