Fix TS2571 errors in BotBuilder-bf-generate-JS (#3472)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Try fixing catch var error TS2571

* Fix catch var error TS2571 2

* Fix error TS2345

* Fix more error TS2571: Object is of type 'unknown'.

* Fix test/generate.test.ts(326,36): error TS2571

* Fix more error TS2571

* Fix test/swagger.test.ts: error TS2571