Fix TS2345 error in project template generators for TypeScript (#3484)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Fix TS2345 in generator-botbuilder JS.