Fix Component Governance vulnerability ejs v2.7.4 (#3493)
* Fix npm run test error TS2345 for generator

* Revert "Fix npm run test error TS2345 for generator"

This reverts commit e49afb6c1f93f78b1d680827fa819e93434af606.

* Fix Django Component Governance security warning

* Fix Django 2.2 before 2.2.10 has a security vulnerability.

* Upgrade yeaoman-generator for ejs vulnerability fix.

* Revert irrelevant change